#spring.profiles.active = dev
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl
    username: root
    password: Alrahim123@
    useSSL: true
  jpa:
    hibernate:
      # create table while running
      ddl-auto: create
      # show sql at console
    show-sql: true